### ISSUE TITLE
Add alternative way for command, slash command takes hours or longer

### ISSUE THREAD

**Issue by mashwishi** [DiscordBotsReddit/OnceHumanUtilityBot#2]
To be able to run this project will take hours or more to make slash command available globally and user's with no knowledge how discord bot fully work might find this very difficult.

For now I am using prefix version as my alternative

**Comment by DiscordBotsReddit** [comment]
Syncing is instant.  Sync and then reload Discord (restart or use Ctrl+R).  Shows up right away.
